print (' M                M    P P           S S S S S S  ')
print (' M  M          M  M    P    P      S              ')            
print (' M    M      M    M    P      P    S              ')   
print (' M      M   M     M    P     P      S             ')
print (' M        M       M    P P  P         S S S       ') 
print (' M                M    P                    S S   ') 
print (' M                M    P                        S ') 
print (' M                M    P                        S  ') 
print (' M                M    P                      S   ') 
print (' M                M    P             S S S S S    ') 